# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jelly', models.CharField(max_length=50)),
                ('accessed', models.DateTimeField()),
                ('url', models.URLField(verbose_name='URL')),
                ('remote_addr', models.GenericIPAddressField(null=True, verbose_name='Remote address')),
                ('referer', models.TextField(verbose_name='Referer')),
                ('user_agent', models.TextField(verbose_name='User agent')),
                ('get', models.TextField(verbose_name='GET')),
                ('post', models.TextField(verbose_name='POST')),
            ],
        ),
    ]
